package com.mks.yuapigateway;

import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableDubbo
public class YuapiGatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(YuapiGatewayApplication.class, args);
    }

}
