package com.mks.luojiaapi;


import com.mks.luojiaapi.dubbo.DemoService;
import org.apache.dubbo.config.annotation.DubboReference;
import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableDubbo
public class LuojiaapiGatewayApplication {

    @DubboReference
    private DemoService demoService;

    public static void main(String[] args) {
        ConfigurableApplicationContext run = SpringApplication.run(LuojiaapiGatewayApplication.class, args);
        LuojiaapiGatewayApplication bean = run.getBean(LuojiaapiGatewayApplication.class);
        System.out.println(bean.demoService.sayHello("mks"));
    }

}
