server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8092
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: info

dubbo:
  application:
    name: yuapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

